### ISSUE TITLE
Noted items not considered in count

### ISSUE THREAD

**Issue by EverCursed** [Toofifty/rl-goal-tracker#1]
Items present in the inventory, but in noted form, are not counted toward the item goal. 

Reproduce:
1. Find a stack of notable items in the bank
2. Set an item goal for the full count of the stack
3. Withdraw one of the item in note form
4. Every item withdrawn as a note lowers item completion in the tracker

**Comment by Toofifty** [comment]
Fixed in https://github.com/Toofifty/rl-goal-tracker/commit/6ab1f1da06c0cf8e85f0f592f6c5cfdc7b468eeb
