### ISSUE TITLE
Change name of "Goal Tracker" plugin to prevent Runelite Conflict

### ISSUE THREAD

**Issue by Marstead** [Toofifty/rl-goal-tracker#13]
Region Locker also installs a subplugin called "Goal Tracker" for tracking goals related to chunks. Unfortunately, if both Region Locker and this Goal Tracker plugin are installed, both of them break. To fix this, one or the other will need to be renamed. (Also opening this issue under the Region Locker Plugin repo).

**Comment by cecilia-sanare** [comment]
Looks like Region Locker resolved this on their end (https://github.com/slaytostay/region-locker/commit/d17cee41cfccadaafdb45135a19391a8cce09c81) so closing this.
