### ISSUE TITLE
Prospector Percy shop trigger acquiring prospector kit items

### ISSUE THREAD

**Issue by vonpawn** [Toofifty/rl-goal-tracker#14]
### Steps to reproduce

- Create a new goal
- Add the four prospector kit items to that goal
- Trade Prospector Percy

### Expected Results

The goal should not update

### Actual Results

All four goals get marked as completed

### Screenshots

![image](https://user-images.githubusercontent.com/22991617/219365650-40e5e9b2-8564-4e18-ba2c-49f4e43a9ddd.png)

<details>
  <summary>Original Comment</summary>

Steps to reproduce
Create a new goal
Add the four prospector kit items to that goal
Trade Prospector Percy

Expected Results:
The goal should not update

Actual Results:
All four goals get marked as completed

![image](https://user-images.githubusercontent.com/22991617/219365650-40e5e9b2-8564-4e18-ba2c-49f4e43a9ddd.png)

I have not tested other shops to see if this is a general issue for items available in reward shops / npc stores

</details>

**Comment by cecilia-sanare** [comment]
Goal Tracker will now only track items in the following inventories:

- Player Inventory (Including equipment)
- Bank
- Seed Vault
- Group Ironman Storage

Resolved via 8e1cfba9c4f8e254670fd96bb95320b0cdfab420
