### ISSUE TITLE
Add a way to delete goals in the main branch.

### ISSUE THREAD

**Issue by raron12** [Toofifty/rl-goal-tracker#16]
Currently you cannot right click goals, (it just registers as left click). Either enable right clicking them, or add a delete button someplace inside of them. Reading the open issues, this should be fixed in some of the branches, but it is not fixed in the main branch.

**Comment by cecilia-sanare** [comment]
Closing as duplicate of #3, fixes were made but never actually deployed to Plugin Hub.
I'll be deploying them shortly.
