### ISSUE TITLE
Right click on quick added tasks counts as left click

### ISSUE THREAD

**Issue by EverCursed** [Toofifty/rl-goal-tracker#2]
Right clicking on a task added via the "Quick add" option will toggle the task completion along with bringing up the right click menu. 

Reproduce:
1. Create a goal. Add a task to the goal using "Quick add".
2. Right click on the task added to the list. The task is toggled and the right click menu is brought up. 

Expected behavior:
Bring up right click menu without toggling the task.

**Comment by Toofifty** [comment]
Should be fixed in https://github.com/Toofifty/rl-goal-tracker/commit/5011d448dcbbedbb76f919acebbfae8e6aa530df

If you can spin up a dev environment, do you mind quickly testing it? If not I'll just release it tomorrow(ish)

**Comment by EverCursed** [comment]
This commit works correctly. This addresses both this and #3. You can close this if you feel like this is sorted out. 

That being said, the master branch is currently busted (looks like screen regions are not updating correctly?). So I can't say that it is fixed, but the specific commit 5011d44 fixes the problem.

**Comment by cecilia-sanare** [comment]
Closing as this will be deployed to Plugin Hub upon the approval of https://github.com/runelite/plugin-hub/pull/5339
