### ISSUE TITLE
[Bug]: Background of side panel doesn't update on open

### ISSUE THREAD

**Issue by VexyRS** [Toofifty/rl-goal-tracker#21]
### Steps to Reproduce

Open any side panel plugin
Open Goal Tracker plugin

Result in picture
![image](https://github.com/Toofifty/rl-goal-tracker/assets/48223567/14474ded-0770-43a7-9ce0-cd5d4c3e2d04)

### Expected Results

No jank

### Actual Results

Jank

**Comment by cecilia-sanare** [comment]
Just looking into this now and I'm not able to reproduce it on my end.
Do you have any other information you can share that might help?

**Comment by VexyRS** [comment]
The issue seems to have resolved itself with a recent update of the RuneLite client. I can no longer reproduce the issue.

**Comment by cecilia-sanare** [comment]
Thanks for letting me know I'm going to close this issue then! Glad it resolved itself!
