### ISSUE TITLE
Add a way to remove a goal

### ISSUE THREAD

**Issue by EverCursed** [Toofifty/rl-goal-tracker#3]
There is currently no method to remove a goal from the list. After adding a goal to test how the plugin works, there is no way to remove it afterwards. It would also be good to have a way to reduce clutter on the goal screen.

**Comment by Toofifty** [comment]
Hey @EverCursed, thanks for submitting some issues :)

I'm looking into #1 and #2, though I'm not sure if this one is a bug. You should be able to right-click a goal in the goal list, just like in a task list.

> It would also be good to have a way to reduce clutter on the goal screen.

I'm definitely open to suggestions on how to change the layout! I tried to avoid clutter by making the extra options collapsible, but I'm stumped on how to add 3+ more task inputs without using all the available space.

**Comment by EverCursed** [comment]
Hmm, interesting. I've just tried this on a different (Linux) machine, and it works properly there. 

What I was seeing was that right clicking on a goal would count as a left click, open the task list for that goal, and then the task that was under the mouse cursor would bring up the right click menu. 

I wonder if your fix for #2 fixed this as well? I will check again and let you know.

**Comment by Toofifty** [comment]
Yeah most likely the same issue then - https://github.com/Toofifty/rl-goal-tracker/commit/5011d448dcbbedbb76f919acebbfae8e6aa530df would have fixed it

**Comment by EverCursed** [comment]
Confirmed fixed by 5011d44.

**Comment by cecilia-sanare** [comment]
Closing as this will be deployed to Plugin Hub upon the approval of https://github.com/runelite/plugin-hub/pull/5339
