### ISSUE TITLE
Sequential task list

### ISSUE THREAD

**Issue by EverCursed** [Toofifty/rl-goal-tracker#6]
Feature Suggestion

Tasks can be either dependent or independent. An independent task is one which can be completed without affecting any other task. For example:

    Goal: Vorkath Preparation
     95 Ranged
     Archer's Ring(i)
     Bandos Godsword

Any of these tasks can be completed independently of each other. 

Dependent tasks are like a pathway to the ultimate goal, a step by step process. Kind of like writing steps for your code when low on motivation - you write every minor thing so that you can cross things off as you approach your goal. For example:

    Goal: Dragon Hunter Lance
     13,000,000 Coins
     Zamorakian Spear
     300,000 Coins
     Zamorakian Hasta
     57,000,000 Coins
     Hydra's claw
     Dragon Hunter Lance

As you go along you cross off each thing step by step. In this case, it is important not to cross things off out of order. The 300,000 Coins should not be crossed off before you have the spear. 

So there are a few ways this can be done:

Make different kinds of lists - dependent and independent. This could be kind of awkward with the current interface. Would need to find a good place to stick the toggle in. I don't really like this option, but it's the easier one to implement. 

<br>
Have a toggle when adding a task that this task is dependent on what comes before. For example:

    Goal: Full Dragon
     65,000,000 coins   // 1
     ↑ Dragon full helm // 2
     2,500,000 coins    // 3
     ↑ Dragon platebody // 4
     175,000 coins      // 5
     ↑ Dragon platelegs // 6
     
I like this option, and it is also would be quite interesting to implement. Your goal becomes a tree of linked lists. Once you accumulate 2,500,000 coins, both 3 and 5 should be checked off. However, once you purchase the platebody, 4 would be checked and 5 _unchecked_.

There is one difficult problem to figure out and that's how backwards dependencies are calculated: reordering. 

You would also need to recalculate (at least parts of) the graph every time a task is moved. Let's say you completed 5 and 6, and then you moved 6 above 5. 6 would now be dependent on 4, but since 4 is not completed, do we uncheck 6? Or do we just complete the entire sub-list? There are situations where you might want to do either one of those, so we can discuss this more. 

Let me know what you think. I know it's a little bit of work for this one, but it would basically check off almost everything I've wanted from a todo list app _ever_. Also, as a reminder, this is just a suggestion! :smile:

**Comment by Toofifty** [comment]
I like it! It may need to be simplified a bit to implement though, I think it'd require major refactors if it was implemented with a linked list or similar.

My idea is to just toggle this mode on and off, wherever it is in the task list (probably via right click menu). Then, the task will only ever be checked for completion if the task displayed above it is already complete. Could potentially disable reordering completely for lists containing dependent tasks, since it doesn't really make sense to reorder a sequential list midway through completing it.

Does this sound like an OK comprimise?

**Comment by EverCursed** [comment]
Might be worth it to play around with this on a separate branch first. 

Let's do this step by step, as it may become complex fairly quickly. First you should do exactly what you suggested - add a way to tag a task as "dependent". We can then see what issues this causes, how much work it would be to make it usable, what design changes would need to happen to make it work, and whether it is worth proceeding with that idea. It's hard to judge without being able to play around with it :)

If this doesn't work out, we can just scrap the idea. But it's worth investigating. 

----

> Could potentially disable reordering completely for lists containing dependent tasks

Probably not a great idea. It's difficult to explain to the user why they can't reorder, and also makes the list very inflexible (forces either toggling off the dependency to rearrange, or recreating a list). Let's implement the dependent property first, and then see whether this is a good solution or not.

**Comment by jacobboertjes** [comment]
I was just trying to implement a rudimentary version of this feature.

My idea was that a form of "indentation" system could be used.
Essentially, adding a right-click option to indent/unindent the task. Essentially, whatever is indented is a prereq to the previously less indented item. For example:
```
Task 1
    Task 2
    Task 3
Task 4
Task 5
```
Task 1 requires first completing Task 2 & Task 3. Task 4 & 5 have no prereqs. I think for simplicity's sake it should begin with evaluating all tasks even if they have prereqs that aren't completed. It would simply allow the user to organize slightly better but leaves room for changes to evaluation later if desired.

Hypothetically it could be taken even further, maybe allowing even further indentation up to some cap:
```
Task 1
   Task 2
      Task 3
   Task 4
   Task 5
Task 6
```
Or just limited to one level of indentation for now.

I'll report back if I manage to come up with something

**Comment by jacobboertjes** [comment]
@Toofifty what do you think of this? User is able to indent/unindent tasks, I set the max indent to 3 to allow the below example:

![image](https://github.com/Toofifty/rl-goal-tracker/assets/35343044/f6f1bbee-3e83-40d3-87fd-e10a6ccf79c3)

As you can see, I made sure the Goals are not indentable:

![image](https://github.com/Toofifty/rl-goal-tracker/assets/35343044/9370d3b1-66a6-4c8a-b395-6586964b1037)



Should I put up a PR?
