### ISSUE TITLE
Goals not saving

### ISSUE THREAD

**Issue by winiarus** [Toofifty/rl-goal-tracker#8]
Every time RuneLite is closed, the plugin get reset to it's default state, deleting all the goals set. This pretty much makes it unusable. Also, the icon disappears.
![Screenshot 2022-05-28 134648](https://user-images.githubusercontent.com/58342967/170824117-73e81a38-43b1-461f-ae08-bb7dc0590c67.png)

**Comment by GertjanOptios** [comment]
Having the same issue

**Comment by MaskofAmor** [comment]
+1 I added a ton of goals and closed my Runelite now they're all gone. Very frustrating. Not sure if they're recoverable now :/

**Comment by cecilia-sanare** [comment]
Should be resolved with a4497c3694f32b5c6475cab074b143eedb76d1ff.
