### ISSUE TITLE
Plugin hub doesn't have latest commit hash

### ISSUE THREAD

**Issue by Fiffers** [Toofifty/rl-goal-tracker#9]
Hey, I've just noticed that the plugin hub doesn't have the latest commit hash yet, and it's been about two months since the plugin was updated. I'm still experiencing a right-click bug that was seemingly fixed in early April. Could you make a PR in the plugin hub with the latest commit hash? If you're too busy, I could make the PR on your behalf.. I just need your permission first.

**Comment by Toofifty** [comment]
Hey! Sorry I've been MIA - I was planning on a refactor but haven't since had the time or motivation to complete it. The current main branch has a few other issues so I won't be releasing that. I'll work on fixing things over the coming days and hopefully have a new release out some time this week.

**Comment by DrJam** [comment]
Excited for plugin to be fixed, really want to use it atm but the issues make it too frustrating (can't right click lists, changes not saving), good luck!

**Comment by cecilia-sanare** [comment]
Closing as this is just waiting on approval of https://github.com/runelite/plugin-hub/pull/5339
